name: "afce058 Action in Action"
description: "Greets someone and returns always 42."
branding:
  icon: 'bell'
  color: 'red'
inputs:
  who-to-greet: #id of input
    description: "Who to greet"
    required: true
    default: "World"
outputs:
  answer: #id of output
    description: "The answer of everything (always 42)"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}